// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2014.2
// Copyright (C) 2014 Xilinx Inc. All rights reserved.
// 
// ==============================================================

#ifndef __cordic_angles_V_H__
#define __cordic_angles_V_H__


#include <systemc>
using namespace sc_core;
using namespace sc_dt;




#include <iostream>
#include <fstream>

struct cordic_angles_V_ram : public sc_core::sc_module {

  static const unsigned DataWidth = 44;
  static const unsigned AddressRange = 20;
  static const unsigned AddressWidth = 5;

//latency = 1
//input_reg = 1
//output_reg = 0
sc_core::sc_in <sc_lv<AddressWidth> > address0;
sc_core::sc_in <sc_logic> ce0;
sc_core::sc_out <sc_lv<DataWidth> > q0;
sc_core::sc_in<sc_logic> reset;
sc_core::sc_in<bool> clk;


sc_lv<DataWidth> ram[AddressRange];


   SC_CTOR(cordic_angles_V_ram) {
        ram[0] = "0b11001001000011111101101010100000011011000110";
        ram[1] = "0b01110110101100011001110000010001001110101000";
        ram[2] = "0b00111110101101101110101111110001110011011000";
        ram[3] = "0b00011111110101011011101010001111101110111111";
        ram[4] = "0b00001111111110101010110111001110101110000110";
        ram[5] = "0b00000111111111110101010101100000001011101011";
        ram[6] = "0b00000011111111111110101010100000001101100010";
        ram[7] = "0b00000001111111111111110101010000110011100010";
        ram[8] = "0b00000000111111111111111110100001100000101011";
        ram[9] = "0b00000000011111111111111111101110110100011111";
        ram[10] = "0b00000000001111111111111111110000111101111011";
        ram[11] = "0b00000000000111111111111111110010000010101001";
        ram[12] = "0b00000000000011111111111111110000011011100100";
        ram[13] = "0b00000000000001111111111111110001110001011101";
        ram[14] = "0b00000000000000111111111111101110001001100010";
        ram[15] = "0b00000000000000011111111111110000101000011100";
        ram[16] = "0b00000000000000001111111111101111101110011110";
        ram[17] = "0b00000000000000000111111111110001011010111010";
        ram[18] = "0b00000000000000000100000000000001010011001101";
        ram[19] = "0b00000000000000000001111111110001100111100010";


SC_METHOD(prc_write_0);
  sensitive<<clk.pos();
   }


void prc_write_0()
{
    if (ce0.read() == sc_dt::Log_1) 
    {
            if(address0.read().is_01() && address0.read().to_uint()<AddressRange)
              q0 = ram[address0.read().to_uint()];
            else
              q0 = sc_lv<DataWidth>();
    }
}


}; //endmodule


SC_MODULE(cordic_angles_V) {


static const unsigned DataWidth = 44;
static const unsigned AddressRange = 20;
static const unsigned AddressWidth = 5;

sc_core::sc_in <sc_lv<AddressWidth> > address0;
sc_core::sc_in<sc_logic> ce0;
sc_core::sc_out <sc_lv<DataWidth> > q0;
sc_core::sc_in<sc_logic> reset;
sc_core::sc_in<bool> clk;


cordic_angles_V_ram* meminst;


SC_CTOR(cordic_angles_V) {
meminst = new cordic_angles_V_ram("cordic_angles_V_ram");
meminst->address0(address0);
meminst->ce0(ce0);
meminst->q0(q0);

meminst->reset(reset);
meminst->clk(clk);
}
~cordic_angles_V() {
    delete meminst;
}


};//endmodule
#endif
